[target.x86_64-unknown-linux-gnu]
image = "uthng/cross:x86_64-unknown-linux-gnu"

[target.aarch64-unknown-linux-gnu]
image = "uthng/cross:aarch64-unknown-linux-gnu"
[target.aarch64-unknown-linux-gnu.env]
passthrough = [
    "BINDGEN_EXTRA_CLANG_ARGS",
]
